sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.4
- 2.4.4
- 2.5.1

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-5.0
  - gemfiles/Gemfile.rails-5.1
  - gemfiles/Gemfile.rails-5.2

matrix:
  include:
    - rvm: 2.6.4
      gemfile: gemfiles/Gemfile.rails-6.0

env: DATABASE_URL=postgres://postgres@localhost/torque_postgresql_test

before_script:
- psql -c 'create database torque_postgresql_test;' -U postgres -h localhost

# notifications:
#   email:
#   - git@danmcclain.net
addons:
  postgresql: '9.6'
  code_climate:
    repo_token: d21c4c9d0d7ba6a27368b8e25edad911eb1daa03202e69fe2bc2e42a3ed21de3
